import { NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { productionJobSchema, productionJobUpdateSchema } from "@/src/lib/validations/production";
import Material from "@/src/models/Material";
import Order from "@/src/models/Order";
import ProductionJob from "@/src/models/ProductionJob";
import Product from "@/src/models/Product";

type Context = { params: Promise<{ id: string }> };
type Ref = { _id: unknown; name?: string; orderNumber?: string; unit?: string; sku?: string; customer?: unknown };
type JobRecord = { _id: unknown; order: Ref | unknown; product: Ref | unknown; quantity: number; printer: string; material?: Ref | unknown; materialUsed: number; estimatedPrintTime: number; actualPrintTime?: number; status: string; startedAt?: Date; completedAt?: Date; notes?: string; timeline?: { status: string; at: Date }[]; createdAt?: Date; updatedAt?: Date };
function serializeJob(job: JobRecord) { const order = job.order && typeof job.order === "object" ? job.order as Ref : {} as Ref; const product = job.product && typeof job.product === "object" ? job.product as Ref : {} as Ref; const material = job.material && typeof job.material === "object" && "name" in job.material ? job.material as Ref : null; const customer = order.customer && typeof order.customer === "object" && "name" in order.customer ? String(order.customer.name) : "Unknown customer"; return { id: String(job._id), order: { id: String(order._id ?? ""), orderNumber: order.orderNumber ?? "Unknown order", customerName: customer }, product: { id: String(product._id ?? ""), name: product.name ?? "Unknown product", sku: product.sku ?? "" }, quantity: job.quantity, printer: job.printer, material: material ? { id: String(material._id), name: material.name ?? "", unit: material.unit ?? "" } : null, materialUsed: job.materialUsed, estimatedPrintTime: job.estimatedPrintTime, actualPrintTime: job.actualPrintTime, status: job.status, startedAt: job.startedAt, completedAt: job.completedAt, notes: job.notes ?? "", timeline: (job.timeline ?? []).map((event) => ({ status: event.status, at: event.at })), createdAt: job.createdAt, updatedAt: job.updatedAt }; }
async function getId(context: Context) { const { id } = await context.params; return Types.ObjectId.isValid(id) ? id : null; }
async function getJob(id: string) { return ProductionJob.findById(id).populate({ path: "order", populate: { path: "customer", select: "name" } }).populate("product", "name sku").populate("material", "name unit").lean(); }
async function validateReferences(data: { order?: string; product?: string; material?: string }) { if (data.order || data.product) { const [order, product] = await Promise.all([data.order ? Order.findById(data.order) : null, data.product ? Product.findOne({ _id: data.product, active: true }) : null]); if (data.order && !order) throw new Error("Selected order was not found."); if (data.product && !product) throw new Error("Selected product was not found."); if (order && data.product && !order.items.some((item) => String(item.product) === data.product)) throw new Error("Selected product is not part of this order."); } if (data.material && !(await Material.findOne({ _id: data.material, active: true }))) throw new Error("Selected material was not found."); }
export async function GET(_request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid production job id." }, { status: 400 }); try { await connectToDatabase(); const job = await getJob(id); if (!job) return NextResponse.json({ error: "Production job not found." }, { status: 404 }); return NextResponse.json({ job: serializeJob(job) }); } catch { return NextResponse.json({ error: "Unable to load production job." }, { status: 500 }); } }
export async function PUT(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid production job id." }, { status: 400 }); try { const parsed = productionJobSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); await validateReferences(parsed.data); const current = await ProductionJob.findById(id).lean(); if (!current) return NextResponse.json({ error: "Production job not found." }, { status: 404 }); const timeline = parsed.data.status !== current.status ? [...(current.timeline ?? []), { status: parsed.data.status, at: new Date() }] : current.timeline; const timestamps = { ...(parsed.data.status === "printing" && !current.startedAt ? { startedAt: new Date() } : {}), ...(parsed.data.status === "ready" && !current.completedAt ? { completedAt: new Date() } : {}) }; await ProductionJob.findByIdAndUpdate(id, { ...parsed.data, material: parsed.data.material || undefined, timeline, ...timestamps }, { runValidators: true }); const job = await getJob(id); if (!job) return NextResponse.json({ error: "Production job not found after update." }, { status: 404 }); return NextResponse.json({ job: serializeJob(job) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update production job." }, { status: 400 }); } }
export async function PATCH(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid production job id." }, { status: 400 }); try { const parsed = productionJobUpdateSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); await validateReferences(parsed.data); const current = await ProductionJob.findById(id).lean(); if (!current) return NextResponse.json({ error: "Production job not found." }, { status: 404 }); const update: Record<string, unknown> = { ...parsed.data, ...(parsed.data.material !== undefined ? { material: parsed.data.material || undefined } : {}) }; if (parsed.data.status && parsed.data.status !== current.status) { update.timeline = [...(current.timeline ?? []), { status: parsed.data.status, at: new Date() }]; if (parsed.data.status === "printing" && !current.startedAt) update.startedAt = new Date(); if (parsed.data.status === "ready" && !current.completedAt) update.completedAt = new Date(); } const job = await ProductionJob.findByIdAndUpdate(id, update, { new: true, runValidators: true }).populate({ path: "order", populate: { path: "customer", select: "name" } }).populate("product", "name sku").populate("material", "name unit").lean(); if (!job) return NextResponse.json({ error: "Production job not found after update." }, { status: 404 }); return NextResponse.json({ job: serializeJob(job) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update production job." }, { status: 400 }); } }
