import { NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { materialSchema, materialUpdateSchema } from "@/src/lib/validations/inventory";
import Material from "@/src/models/Material";

type Context = { params: Promise<{ id: string }> };
function materialStatus(quantity: number, minimum: number) { return quantity <= 0 ? "Out of Stock" : quantity <= minimum ? "Low Stock" : "In Stock"; }
function serializeMaterial(material: { _id: unknown; name: string; sku: string; unit: string; currentQuantity: number; minimumQuantity: number; costPerUnit: number; supplier?: string; active: boolean }) { return { id: String(material._id), name: material.name, sku: material.sku, unit: material.unit, currentQuantity: material.currentQuantity, minimumQuantity: material.minimumQuantity, costPerUnit: material.costPerUnit, inventoryValue: material.currentQuantity * material.costPerUnit, supplier: material.supplier ?? "", active: material.active, status: materialStatus(material.currentQuantity, material.minimumQuantity) as "In Stock" | "Low Stock" | "Out of Stock" }; }
async function getId(context: Context) { const { id } = await context.params; return Types.ObjectId.isValid(id) ? id : null; }
export async function GET(_request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid material id." }, { status: 400 }); try { await connectToDatabase(); const material = await Material.findById(id).lean(); if (!material) return NextResponse.json({ error: "Material not found." }, { status: 404 }); return NextResponse.json({ material: serializeMaterial(material) }); } catch { return NextResponse.json({ error: "Unable to load material." }, { status: 500 }); } }
export async function PUT(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid material id." }, { status: 400 }); try { const parsed = materialSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const material = await Material.findByIdAndUpdate(id, parsed.data, { new: true, runValidators: true }).lean(); if (!material) return NextResponse.json({ error: "Material not found." }, { status: 404 }); return NextResponse.json({ material: serializeMaterial(material) }); } catch (error) { if (error instanceof Error && "code" in error && error.code === 11000) return NextResponse.json({ error: "A material with this SKU already exists." }, { status: 409 }); return NextResponse.json({ error: "Unable to update material." }, { status: 500 }); } }
export async function PATCH(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid material id." }, { status: 400 }); try { const parsed = materialUpdateSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const material = await Material.findByIdAndUpdate(id, parsed.data, { new: true, runValidators: true }).lean(); if (!material) return NextResponse.json({ error: "Material not found." }, { status: 404 }); return NextResponse.json({ material: serializeMaterial(material) }); } catch { return NextResponse.json({ error: "Unable to update material." }, { status: 500 }); } }
