import { NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { calculateOrderTotals } from "@/src/lib/order-calculations";
import { orderSchema, orderUpdateSchema } from "@/src/lib/validations/order";
import Customer from "@/src/models/Customer";
import Order from "@/src/models/Order";
import Product from "@/src/models/Product";
import TeamMember from "@/src/models/TeamMember";
import { createNotification } from "@/src/lib/notifications";

type Context = { params: Promise<{ id: string }> };
type OrderReference = { _id: unknown; name?: string; phone?: string };
type OrderItemRecord = { product?: { _id: unknown } | unknown; productName: string; sku: string; quantity: number; unitPrice: number; unitCost?: number };
type OrderRecord = { _id: unknown; orderNumber: string; customer?: OrderReference; teamMember?: OrderReference; items: OrderItemRecord[]; channel: string; discount: number; shipping: number; paymentStatus: string; paymentMethod?: string; paidAmount: number; status: string; notes?: string; timeline?: { status: string; at: Date }[]; createdAt?: Date; updatedAt?: Date };
function serializeOrder(order: OrderRecord | null) { if (!order) throw new Error("Order not found."); const customer: OrderReference = order.customer ?? { _id: "", name: "Unknown customer", phone: "" }; const teamMember: OrderReference = order.teamMember ?? { _id: "", name: "Unknown team member" }; const { subtotal, total } = calculateOrderTotals(order); return { id: String(order._id), orderNumber: order.orderNumber, customer: { id: String(customer._id), name: customer.name ?? "Unknown customer", phone: customer.phone ?? "" }, teamMember: { id: String(teamMember._id), name: teamMember.name ?? "Unknown team member" }, items: order.items.map((item) => ({ productId: String(item.product && typeof item.product === "object" && "_id" in item.product ? item.product._id : item.product), name: item.productName, sku: item.sku, quantity: item.quantity, unitPrice: item.unitPrice })), channel: order.channel, subtotal, discount: order.discount, shipping: order.shipping, total, paymentStatus: order.paymentStatus, paymentMethod: order.paymentMethod, paidAmount: order.paidAmount, status: order.status, notes: order.notes ?? "", timeline: (order.timeline ?? []).map((event) => ({ status: event.status, at: event.at })), createdAt: order.createdAt, updatedAt: order.updatedAt }; }
async function getId(context: Context) { const { id } = await context.params; return Types.ObjectId.isValid(id) ? id : null; }
async function getOrder(id: string) { return Order.findById(id).populate("customer", "name phone").populate("teamMember", "name").lean(); }
async function prepareItems(items: { product: string; quantity: number }[]) { const products = await Product.find({ _id: { $in: items.map((item) => item.product) }, active: true }).lean(); const byId = new Map(products.map((product) => [String(product._id), product])); if (byId.size !== new Set(items.map((item) => item.product)).size) throw new Error("One or more selected products are unavailable."); return items.map((item) => { const product = byId.get(item.product)!; return { product: product._id, productName: product.name, sku: product.sku, quantity: item.quantity, unitPrice: product.sellingPrice, unitCost: product.materialCost + product.productionCost + product.packagingCost + product.otherCost }; }); }

export async function GET(_request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid order id." }, { status: 400 }); try { await connectToDatabase(); const order = await getOrder(id); if (!order) return NextResponse.json({ error: "Order not found." }, { status: 404 }); return NextResponse.json({ order: serializeOrder(order) }); } catch { return NextResponse.json({ error: "Unable to load order." }, { status: 500 }); } }

export async function PUT(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid order id." }, { status: 400 }); try { const parsed = orderSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const [customer, teamMember] = await Promise.all([Customer.findOne({ _id: parsed.data.customer, status: "active" }), TeamMember.findOne({ _id: parsed.data.teamMember, active: true })]); if (!customer || !teamMember) return NextResponse.json({ error: "Selected customer or team member is unavailable." }, { status: 400 }); const current = await Order.findById(id).lean(); if (!current) return NextResponse.json({ error: "Order not found." }, { status: 404 }); const items = await prepareItems(parsed.data.items); const timeline = parsed.data.status !== current.status ? [...(current.timeline ?? []), { status: parsed.data.status, at: new Date() }] : current.timeline; await Order.findByIdAndUpdate(id, { ...parsed.data, items, timeline }, { runValidators: true }); const order = await getOrder(id); if (parsed.data.status !== current.status) await createNotification({ type: "order_status_changed", title: "Order status changed", message: `${order?.orderNumber} is now ${parsed.data.status}.`, entityType: "order", entityId: id, dedupeKey: `order_status_changed:${id}:${parsed.data.status}` }); if (parsed.data.paidAmount > current.paidAmount || parsed.data.paymentStatus === "paid" && current.paymentStatus !== "paid") await createNotification({ type: "payment_received", title: "Payment received", message: `Payment received for ${order?.orderNumber}.`, entityType: "order", entityId: id, dedupeKey: `payment_received:${id}:${parsed.data.paidAmount}` }); return NextResponse.json({ order: serializeOrder(order) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update order." }, { status: 500 }); } }

export async function PATCH(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid order id." }, { status: 400 }); try { const parsed = orderUpdateSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const current = await Order.findById(id).lean(); if (!current) return NextResponse.json({ error: "Order not found." }, { status: 404 }); const update: Record<string, unknown> = { ...parsed.data }; if (parsed.data.status && parsed.data.status !== current.status) update.timeline = [...(current.timeline ?? []), { status: parsed.data.status, at: new Date() }]; const order = await Order.findByIdAndUpdate(id, update, { new: true, runValidators: true }).populate("customer", "name phone").populate("teamMember", "name").lean(); if (parsed.data.status && parsed.data.status !== current.status) await createNotification({ type: "order_status_changed", title: "Order status changed", message: `${order?.orderNumber} is now ${parsed.data.status}.`, entityType: "order", entityId: id, dedupeKey: `order_status_changed:${id}:${parsed.data.status}` }); if (parsed.data.paidAmount !== undefined && parsed.data.paidAmount > current.paidAmount || parsed.data.paymentStatus === "paid" && current.paymentStatus !== "paid") await createNotification({ type: "payment_received", title: "Payment received", message: `Payment received for ${order?.orderNumber}.`, entityType: "order", entityId: id, dedupeKey: `payment_received:${id}:${parsed.data.paidAmount ?? "paid"}` }); return NextResponse.json({ order: serializeOrder(order) }); } catch { return NextResponse.json({ error: "Unable to update order." }, { status: 500 }); } }
