import { NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { expenseSchema, expenseUpdateSchema } from "@/src/lib/validations/expense";
import Expense from "@/src/models/Expense";
import TeamMember from "@/src/models/TeamMember";

type Context = { params: Promise<{ id: string }> };
type ExpenseRecord = { _id: unknown; category: string; description: string; amount: number; date: Date; paymentMethod: string; addedBy?: unknown; notes?: string; receiptReference?: string; status: string; createdAt?: Date; updatedAt?: Date };
function serializeExpense(expense: ExpenseRecord) { const addedBy = expense.addedBy && typeof expense.addedBy === "object" && "name" in expense.addedBy && "_id" in expense.addedBy ? expense.addedBy as { _id: unknown; name: string } : null; return { id: String(expense._id), category: expense.category, description: expense.description, amount: expense.amount, date: expense.date, paymentMethod: expense.paymentMethod, addedBy: addedBy ? { id: String(addedBy._id), name: addedBy.name } : null, notes: expense.notes ?? "", receiptReference: expense.receiptReference ?? "", status: expense.status, createdAt: expense.createdAt, updatedAt: expense.updatedAt }; }
async function getId(context: Context) { const { id } = await context.params; return Types.ObjectId.isValid(id) ? id : null; }
async function validateAddedBy(addedBy?: string) { if (!addedBy) return true; return Boolean(await TeamMember.findOne({ _id: addedBy, active: true }).select("_id")); }

export async function GET(_request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid expense id." }, { status: 400 }); try { await connectToDatabase(); const expense = await Expense.findById(id).populate("addedBy", "name").lean(); if (!expense) return NextResponse.json({ error: "Expense not found." }, { status: 404 }); return NextResponse.json({ expense: serializeExpense(expense) }); } catch { return NextResponse.json({ error: "Unable to load expense." }, { status: 500 }); } }

export async function PUT(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid expense id." }, { status: 400 }); try { const parsed = expenseSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); if (!(await validateAddedBy(parsed.data.addedBy))) return NextResponse.json({ error: "Selected team member was not found." }, { status: 400 }); const { addedBy, ...input } = parsed.data; const expense = await Expense.findByIdAndUpdate(id, { ...input, addedBy: addedBy || undefined }, { new: true, runValidators: true }).populate("addedBy", "name").lean(); if (!expense) return NextResponse.json({ error: "Expense not found." }, { status: 404 }); return NextResponse.json({ expense: serializeExpense(expense) }); } catch { return NextResponse.json({ error: "Unable to update expense." }, { status: 500 }); } }

export async function PATCH(request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid expense id." }, { status: 400 }); try { const parsed = expenseUpdateSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); if (!(await validateAddedBy(parsed.data.addedBy))) return NextResponse.json({ error: "Selected team member was not found." }, { status: 400 }); const { addedBy, ...input } = parsed.data; const expense = await Expense.findByIdAndUpdate(id, { ...input, ...(addedBy !== undefined ? { addedBy: addedBy || undefined } : {}) }, { new: true, runValidators: true }).populate("addedBy", "name").lean(); if (!expense) return NextResponse.json({ error: "Expense not found." }, { status: 404 }); return NextResponse.json({ expense: serializeExpense(expense) }); } catch { return NextResponse.json({ error: "Unable to update expense." }, { status: 500 }); } }

export async function DELETE(_request: Request, context: Context) { const id = await getId(context); if (!id) return NextResponse.json({ error: "Invalid expense id." }, { status: 400 }); try { await connectToDatabase(); const expense = await Expense.findByIdAndUpdate(id, { status: "voided" }, { new: true, runValidators: true }).populate("addedBy", "name").lean(); if (!expense) return NextResponse.json({ error: "Expense not found." }, { status: 404 }); return NextResponse.json({ expense: serializeExpense(expense) }); } catch { return NextResponse.json({ error: "Unable to void expense." }, { status: 500 }); } }
