import { NextResponse } from "next/server";
import mongoose from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { inventoryAdjustmentSchema } from "@/src/lib/validations/inventory";
import InventoryTransaction from "@/src/models/InventoryTransaction";
import Material from "@/src/models/Material";
import TeamMember from "@/src/models/TeamMember";
import { createNotification } from "@/src/lib/notifications";

export const runtime = "nodejs";
type InventoryTransactionRecord = { _id: unknown; material?: unknown; product?: unknown; quantityChange: number; reason: string; date: Date; user?: unknown; notes?: string };
function serializeTransaction(transaction: InventoryTransactionRecord) { const material = transaction.material && typeof transaction.material === "object" && "_id" in transaction.material ? transaction.material as { _id: unknown; name: string; sku: string } : null; const product = transaction.product && typeof transaction.product === "object" && "_id" in transaction.product ? transaction.product as { _id: unknown; name: string; sku: string } : null; const user = transaction.user && typeof transaction.user === "object" && "_id" in transaction.user && "name" in transaction.user ? transaction.user as { _id: unknown; name: string } : null; const trackedItem = material ?? product; return { id: String(transaction._id), material: { id: String(trackedItem?._id ?? ""), name: trackedItem?.name ?? "Unknown item", sku: trackedItem?.sku ?? "" }, product: product ? { id: String(product._id), name: product.name, sku: product.sku } : null, quantityChange: transaction.quantityChange, reason: transaction.reason, date: transaction.date, user: user ? { id: String(user._id), name: user.name } : null, notes: transaction.notes ?? "" }; }
export async function GET(request: Request) { try { await connectToDatabase(); const params = new URL(request.url).searchParams; const material = params.get("material"); const product = params.get("product"); const filter = material ? { material } : product ? { product } : {}; const transactions = await InventoryTransaction.find(filter).populate("material", "name sku").populate("product", "name sku").populate("user", "name").sort({ date: -1 }).limit(50).lean(); return NextResponse.json({ transactions: transactions.map(serializeTransaction) }); } catch { return NextResponse.json({ error: "Unable to load inventory history." }, { status: 500 }); } }
export async function POST(request: Request) { const parsed = inventoryAdjustmentSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const session = await mongoose.startSession(); try { let updatedMaterialId: unknown = null; let updatedQuantity: number | null = null; let materialName = "Inventory"; let minimumQuantity = 0; await session.withTransaction(async () => { const material = await Material.findById(parsed.data.material).session(session); if (!material) throw new Error("Material not found."); materialName = material.name; minimumQuantity = material.minimumQuantity; if (parsed.data.user) { const user = await TeamMember.findOne({ _id: parsed.data.user, active: true }).session(session); if (!user) throw new Error("Selected user was not found."); } if (material.currentQuantity + parsed.data.quantityChange < 0) throw new Error("Stock cannot become negative."); const updatedMaterial = await Material.findOneAndUpdate({ _id: parsed.data.material, currentQuantity: { $gte: Math.max(0, -parsed.data.quantityChange) } }, { $inc: { currentQuantity: parsed.data.quantityChange } }, { new: true, session }); if (!updatedMaterial) throw new Error("Stock changed before this adjustment could be applied."); updatedMaterialId = updatedMaterial._id; updatedQuantity = updatedMaterial.currentQuantity; await InventoryTransaction.create([{ ...parsed.data, user: parsed.data.user || undefined }], { session }); }); if (updatedQuantity === null) throw new Error("Material adjustment failed."); await createNotification({ type: "inventory_adjusted", title: "Inventory adjusted", message: `${materialName} changed by ${parsed.data.quantityChange}.`, entityType: "inventory", entityId: String(updatedMaterialId), dedupeKey: `inventory_adjusted:${updatedMaterialId}:${updatedQuantity}:${parsed.data.reason}` }); if (updatedQuantity <= minimumQuantity) await createNotification({ type: "inventory_low_stock", title: "Low stock", message: `${materialName} is at or below its minimum level.`, entityType: "inventory", entityId: String(updatedMaterialId), dedupeKey: `inventory_low_stock:${updatedMaterialId}:${updatedQuantity}` }); return NextResponse.json({ material: { id: String(updatedMaterialId), currentQuantity: updatedQuantity } }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to adjust stock." }, { status: 400 }); } finally { await session.endSession(); } }
