import { NextResponse } from "next/server";
import mongoose from "mongoose";
import { connectToDatabase } from "@/src/lib/mongodb";
import { inventoryAdjustmentSchema } from "@/src/lib/validations/inventory";
import InventoryTransaction from "@/src/models/InventoryTransaction";
import Material from "@/src/models/Material";
import TeamMember from "@/src/models/TeamMember";

export const runtime = "nodejs";
type InventoryTransactionRecord = { _id: unknown; material: unknown; quantityChange: number; reason: string; date: Date; user?: unknown; notes?: string };
function serializeTransaction(transaction: InventoryTransactionRecord) { const material = transaction.material as { _id: unknown; name: string; sku: string }; const user = transaction.user && typeof transaction.user === "object" && "_id" in transaction.user && "name" in transaction.user ? transaction.user as { _id: unknown; name: string } : null; return { id: String(transaction._id), material: { id: String(material._id), name: material.name, sku: material.sku }, quantityChange: transaction.quantityChange, reason: transaction.reason, date: transaction.date, user: user ? { id: String(user._id), name: user.name } : null, notes: transaction.notes ?? "" }; }
export async function GET(request: Request) { try { await connectToDatabase(); const params = new URL(request.url).searchParams; const material = params.get("material"); const filter = material ? { material } : {}; const transactions = await InventoryTransaction.find(filter).populate("material", "name sku").populate("user", "name").sort({ date: -1 }).limit(50).lean(); return NextResponse.json({ transactions: transactions.map(serializeTransaction) }); } catch { return NextResponse.json({ error: "Unable to load inventory history." }, { status: 500 }); } }
export async function POST(request: Request) { const parsed = inventoryAdjustmentSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const session = await mongoose.startSession(); try { let updatedMaterialId: unknown = null; let updatedQuantity: number | null = null; await session.withTransaction(async () => { const material = await Material.findById(parsed.data.material).session(session); if (!material) throw new Error("Material not found."); if (parsed.data.user) { const user = await TeamMember.findOne({ _id: parsed.data.user, active: true }).session(session); if (!user) throw new Error("Selected user was not found."); } if (material.currentQuantity + parsed.data.quantityChange < 0) throw new Error("Stock cannot become negative."); const updatedMaterial = await Material.findOneAndUpdate({ _id: parsed.data.material, currentQuantity: { $gte: Math.max(0, -parsed.data.quantityChange) } }, { $inc: { currentQuantity: parsed.data.quantityChange } }, { new: true, session }); if (!updatedMaterial) throw new Error("Stock changed before this adjustment could be applied."); updatedMaterialId = updatedMaterial._id; updatedQuantity = updatedMaterial.currentQuantity; await InventoryTransaction.create([{ ...parsed.data, user: parsed.data.user || undefined }], { session }); }); if (updatedQuantity === null) throw new Error("Material adjustment failed."); return NextResponse.json({ material: { id: String(updatedMaterialId), currentQuantity: updatedQuantity } }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to adjust stock." }, { status: 400 }); } finally { await session.endSession(); } }
