import { NextResponse } from "next/server";
import { connectToDatabase } from "@/src/lib/mongodb";
import { productionJobSchema } from "@/src/lib/validations/production";
import { dateRangeFilter, getReportingRange } from "@/src/lib/reporting-period";
import Material from "@/src/models/Material";
import Order from "@/src/models/Order";
import ProductionJob from "@/src/models/ProductionJob";
import Product from "@/src/models/Product";
import { createNotification } from "@/src/lib/notifications";

export const runtime = "nodejs";

type Ref = { _id: unknown; name?: string; orderNumber?: string; unit?: string; sku?: string; customer?: unknown };
type JobRecord = { _id: unknown; order: Ref | unknown; product: Ref | unknown; quantity: number; printer: string; material?: Ref | unknown; materialUsed: number; estimatedPrintTime: number; actualPrintTime?: number; status: string; startedAt?: Date; completedAt?: Date; notes?: string; timeline?: { status: string; at: Date }[]; createdAt?: Date; updatedAt?: Date };
function serializeJob(job: JobRecord) { const order = job.order && typeof job.order === "object" ? job.order as Ref : {} as Ref; const product = job.product && typeof job.product === "object" ? job.product as Ref : {} as Ref; const material = job.material && typeof job.material === "object" && "name" in job.material ? job.material as Ref : null; return { id: String(job._id), order: { id: String(order._id ?? ""), orderNumber: order.orderNumber ?? "Unknown order", customerName: order.name ?? "Unknown customer" }, product: { id: String(product._id ?? ""), name: product.name ?? "Unknown product", sku: product.sku ?? "" }, quantity: job.quantity, printer: job.printer, material: material ? { id: String(material._id), name: material.name ?? "", unit: material.unit ?? "" } : null, materialUsed: job.materialUsed, estimatedPrintTime: job.estimatedPrintTime, actualPrintTime: job.actualPrintTime, status: job.status, startedAt: job.startedAt, completedAt: job.completedAt, notes: job.notes ?? "", timeline: (job.timeline ?? []).map((event) => ({ status: event.status, at: event.at })), createdAt: job.createdAt, updatedAt: job.updatedAt }; }
async function populateJob(id: unknown) { return ProductionJob.findById(id).populate({ path: "order", populate: { path: "customer", select: "name" } }).populate("product", "name sku").populate("material", "name unit").lean(); }

export async function GET(request: Request) { try { const range = getReportingRange(new URL(request.url).searchParams); await connectToDatabase(); const filter = range.kind === "all" ? {} : { createdAt: dateRangeFilter(range) }; const jobs = await ProductionJob.find(filter).populate({ path: "order", populate: { path: "customer", select: "name" } }).populate("product", "name sku").populate("material", "name unit").sort({ createdAt: -1 }).lean(); return NextResponse.json({ jobs: jobs.map((job) => { const serialized = serializeJob(job); const order = job.order && typeof job.order === "object" ? job.order as Ref : {} as Ref; const customer = order.customer && typeof order.customer === "object" && "name" in order.customer ? String(order.customer.name) : "Unknown customer"; return { ...serialized, order: { ...serialized.order, customerName: customer } }; }) }); } catch (error) { const invalid = error instanceof Error && error.message === "Invalid reporting period."; return NextResponse.json({ error: invalid ? error.message : "Unable to load production jobs." }, { status: invalid ? 400 : 500 }); } }

export async function POST(request: Request) { try { const parsed = productionJobSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Validation failed.", issues: parsed.error.flatten().fieldErrors }, { status: 400 }); await connectToDatabase(); const [order, product] = await Promise.all([Order.findById(parsed.data.order), Product.findOne({ _id: parsed.data.product, active: true })]); if (!order) return NextResponse.json({ error: "Selected order was not found." }, { status: 400 }); if (!product || !order.items.some((item) => String(item.product) === parsed.data.product)) return NextResponse.json({ error: "Selected product is not part of this order." }, { status: 400 }); if (parsed.data.material) { const material = await Material.findOne({ _id: parsed.data.material, active: true }); if (!material) return NextResponse.json({ error: "Selected material was not found." }, { status: 400 }); } const job = await ProductionJob.create({ ...parsed.data, material: parsed.data.material || undefined, timeline: [{ status: parsed.data.status, at: new Date() }] }); const populated = await populateJob(job._id); if (!populated) throw new Error("Created production job could not be loaded."); const serialized = serializeJob(populated); const populatedOrder = populated.order && typeof populated.order === "object" ? populated.order as Ref : {} as Ref; const customer = populatedOrder.customer && typeof populatedOrder.customer === "object" && "name" in populatedOrder.customer ? String(populatedOrder.customer.name) : "Unknown customer"; await createNotification({ type: "production_job_created", title: "Production job created", message: `Production started for ${serialized.product.name}.`, entityType: "production", entityId: String(job._id), dedupeKey: `production_job_created:${job._id}` }); if (parsed.data.status === "ready") await createNotification({ type: "production_job_completed", title: "Production job completed", message: `${serialized.product.name} is ready.`, entityType: "production", entityId: String(job._id), dedupeKey: `production_job_completed:${job._id}` }); return NextResponse.json({ job: { ...serialized, order: { ...serialized.order, customerName: customer } } }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create production job." }, { status: 500 }); } }
